name: Pytest

on: push

permissions:
  contents: read

env:
  DEBUG: 0
  DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

  OSU_CLIENT_ID: ${{ secrets.OSU_CLIENT_ID }}
  OSU_CLIENT_SECRET: ${{ secrets.OSU_CLIENT_SECRET }}
  OSU_CLIENT_REDIRECT_URI: ${{ secrets.OSU_CLIENT_REDIRECT_URI }}

  PGDATABASE: postgres
  PGUSER: postgres
  PGPASSWORD: postgres
  PGHOST: 127.0.0.1
  PGPORT: 5432

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
        environment: production-build
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Start postgresql
      run: |
        sudo systemctl start postgresql.service
    - name: Test with pytest
      working-directory: ./otdb
      run: |
        pytest
